version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/public/build
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: laravelpassword

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
